---
- name: Include correct package names
  include_vars: "{{ ansible_distribution }}.yml"
  when: wtd_mariadb_repository == "default"
  tags:
    - mariadb

- name: Include correct upstream package names
  include_vars: repo_mariadb.yml
  when: wtd_mariadb_repository == "repo_mariadb"
  tags:
    - mariadb

- name: Install MariaDB
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wtd_mariadb_packages }}"
  tags:
    - mariadb

- name: Include Configuration Tasks
  include_tasks: configure.yml

- name: Enable and Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
  tags:
    - mariadb

- name: Include Secure Installation Tasks
  include_tasks: mysql_secure_installation.yml
