---
- name: Select packages
  include_tasks: select_packages.yml

- name: Include cleanup MariaDB packages if repo-mariadb is enabled
  include_tasks: cleanup_packages_repo_enabled.yml
  when: wtd_repo_mariadb_enabled and wtd_repo_mariadb_added.changed

- name: Include cleanup MariaDB packages if repo-mariadb is disabled
  include_tasks: cleanup_packages_repo_disabled.yml
  when: not wtd_repo_mariadb_enabled and wtd_repo_mariadb_removed.changed

- name: Install ansible dependency MySQL-python
  package:
    name: MySQL-python
    state: present

- name: Install MariaDB
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ wtd_mariadb_packages }}"

- name: Configure /etc/my.cnf
  template:
    src: my-cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MariaDB service

- name: Configure /etc/my.cnf.d
  file:
    path: /etc/my.cnf.d
    state: directory
    mode: 0755
  notify:
    - Restart MariaDB service

- name: Configure /etc/my.cnf.d/server.cnf
  template:
    src: server-cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MariaDB service

- name: Start MariaDB and enable service
  service:
    name: "{{ wtd_mariadb_service }}"
    state: started
    enabled: yes

- name: Include mysql_secure_installation
  include_tasks: mysql_secure_installation.yml

