---
- name: Install MariaDB
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ wtd_mariadb_packages }}'

- name: Install ansible dependency MySQL-python
  package:
    name: MySQL-python
    state: present

- name: Configure /etc/my.cnf
  template:
    src: my-cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MariaDB service

- name: Configure /etc/my.cnf.d
  file:
    path: /etc/my.cnf.d
    state: directory
    mode: 0755
  notify:
    - Restart MariaDB service

- name: Configure /etc/my.cnf.d/server.cnf
  template:
    src: server-cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MariaDB service

- name: Start MariaDB and enable service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Include mysql_secure_installation
  include_tasks: mysql_secure_installation.yml

